// Assignment Code
var generateBtn = document.querySelector("#generate");

// Creating variables with strings of included characters to draw from
var upperList = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
var lowerList = 'abcdefghijklmnopqrstuvwxyz';
var numberList = '0123456789';
var symbolList = '!#$%&()*+,-./:;<=>?@[]^{|}~';



// Write password to the #password input
function writePassword() {
  // calling the generatePassword function and assigning the outcome a variable
  var password = generatePassword();
  // assigning variable to the password field
  var passwordText = document.querySelector("#password");
  // function result to password field
  passwordText.value = password;

 return;
}

// function to generate the password
function generatePassword() {
  // creating empty string variables
  var passAmalg = '';
  var passRandom = [];
  var guaranteeAm = [];

  // window pop-ups with the user input choice and length content 
  console.log("popups first");
  var upperCaseSel = confirm("Include uppercase letters?");
  var lowerCaseSel = confirm("Include lowercase letters?");
  var numberSel = confirm("Include numbers?");
  var symbolSel = confirm("Include symbols?");
  var lengthSel = prompt("Please state desired password length.", "8-128");
  
  // ensuring that length is considered an integer and not a string
  lengthSel = parseInt(lengthSel);

  // if length is not a number or if it is greater than 8/less than 128 - returning nothing to ensure nothing is sent to password field
  if (isNaN(lengthSel)) {
    console.log("length not number");
    alert("Length is not a number! Please enter a number between 8-128.");
    return "";
  } else if (lengthSel < 8 || lengthSel > 128) {
    console.log("length within bounds");
    alert("Length must be between 8-128!");
    return "";
  }

  // if none of the options are chosen (all false), returns an alert that an option must be chosen - returning nothing to ensure nothing is sent to password field
  if (upperCaseSel === false && lowerCaseSel === false && numberSel === false && symbolSel === false) {
    alert("You must choose at least one option!");
    return "";
  }
  
  // if upper case is confirmed (true), add upper case string to empty passAmalg string and push a random selection from the upperList string generated by "random" function to the guaranteedAm array
  if (upperCaseSel) {
    passAmalg = passAmalg.concat(upperList);
    guaranteeAm.push(random(upperList));
  }

  // if lower case is confirmed (true), add lower case string to empty passAmalg string and push a random selection from the lowerList string generated by "random" function to the guaranteedAm array
  if (lowerCaseSel) {
    passAmalg = passAmalg.concat(lowerList);
    guaranteeAm.push(random(lowerList));
  }

  // if number is confirmed (true), add number string to empty passAmalg string and push a random selection from the numberList string generated by "random" function to the guaranteedAm array
  if (numberSel) {
    passAmalg = passAmalg.concat(numberList);
    guaranteeAm.push(random(numberList));
  }
  
  // if symbol is confirmed (true), add symbol string to empty passAmalg string and push a random selection from the symbolList string generated by "random" function to the guaranteedAm array
  if (symbolSel) {
    passAmalg = passAmalg.concat(symbolList);
    guaranteeAm.push(random(symbolList));
  }

  // for-loop to radomize the final resulting passAmalg string and loop it for as many characters as have been chosen by the user in the "lengthSel" prompt. Randomized characters then pushed to the "passRandom" array until the loop is completed
  for (var i=0; i < lengthSel; i++) {
    passRandom.push(random(passAmalg));
  }

  // for loop ensuring that the first variables (as many as have been chosen by user) in the passRandom array are variables from the guaranteeAm array to ensure that all selections chosen by user are represented in the result.
  for (var i = 0; i < guaranteeAm.length; i++) {
    passRandom[i] = guaranteeAm[i];
  }
  // returns the final passRandom array after it's gone through the for-loop above and joins it to a string in order to align with the type of the different character lists
  return passRandom.join('');
}

// randomizing function to streamline the many instances of generating a random character within an array or string. Math.random uses a random decimal and multiplies it by the length of the string/array (x) to get a number, which Math.floor rounds to a whole number to be used to choose the position of the character in the string/array.
function random (x) {
  var index = Math.floor(Math.random() * x.length);
  var element = x[index];
  return element;
}

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);